safe: true
timezone: Europe/Stockholm
markdown: kramdown

title: Interpreti Veneziani
description: Website dedicated to the music of Venetian baroque ensemble Interpreti Veneziani.
live_url: https://sanvidal.org
live_hostname: sanvidal.org
author: Markus Amalthea Magnuson
email: info@sanvidal.org
google_analytics_id: UA-46665893-1
